### PR TITLE
Clone the ResourceManager type from virtual-kubelet

### LINKED ISSUE #1: Unable to import Resource Manager from virtual-kubelet 1.0
The package `github.com/virtual-kubelet/virtual-kubelet/manager` has been moved to `github.com/virtual-kubelet/internal/manager`.  This project currently has dependencies on that now internal package.

```bash
$ git diff go.mod
diff --git a/go.mod b/go.mod
index fb5ee7e..2865e9f 100644
--- a/go.mod
+++ b/go.mod
@@ -10,7 +10,7 @@ require (
        github.com/sirupsen/logrus v1.4.2
        github.com/spf13/cobra v0.0.5
        github.com/spf13/pflag v1.0.3
-       github.com/virtual-kubelet/virtual-kubelet v0.11.1
+       github.com/virtual-kubelet/virtual-kubelet v1.0.0
        go.opencensus.io v0.20.2
        k8s.io/api v0.0.0-20190222213804-5cb15d344471
        k8s.io/apimachinery v0.0.0-20190221213512-86fb29eff628
```

```bash
$ go build
go: finding github.com/virtual-kubelet/virtual-kubelet/manager latest
provider/store.go:6:2: unknown import path "github.com/virtual-kubelet/virtual-kubelet/manager": cannot find module providing package github.com/virtual-kubelet/virtual-kubelet/manager
```

### PR DESCRIPTION
**Pull request by gabrielhartmann**
This change allows migration to the v1.0 release of virtual-kubelet.  Resolves issue #1 
Closes #1

### CODE REVIEW

**Comment by cpuguy83** [comment]
@lucperkins

What's the method process for setting up the CLA checker on this repo?

**Comment by gabrielhartmann** [comment]
@cpuguy83: Anyone else's review needed before merge?

**Comment by cpuguy83** [comment]
I just want to get the CLA checker in and we can merge, sorry for the wait!

**Comment by gabrielhartmann** [comment]
No worries.

**Comment by gabrielhartmann** [comment]
@cpuguy83 : Any news here?

**Comment by cpuguy83** [comment]
Yay, looks like it's added.

**Comment by cpuguy83** [comment]
@gabrielhartmann Thanks for your patience!

**Comment by gabrielhartmann** [comment]
Thanks @cpuguy83

**Pull request merged**
