### PR TITLE
feat: wait for node controller started

### PR DESCRIPTION
**Pull request by LeoLiuYan**

### CODE REVIEW

**Comment by LeoLiuYan** [comment]
cc @cpuguy83

**Comment by cpuguy83** [comment]
Still, this should go in your own code, not at the library level.

**Comment by LeoLiuYan** [comment]
> Still, this should go in your own code, not at the library level.

First, controller's ready function not expose to who ues the node-cli library.  And notify to systemd also should do in the node-cli just like kube-apiserver or kube-scheduer do.

**Comment by LeoLiuYan** [comment]
// Wait for node controller ready
<-nodeRunner.Ready()

I also think we should wait for controller ready after  https://github.com/virtual-kubelet/node-cli/blob/master/internal/commands/root/root.go#L231.

**Comment by feiskyer** [comment]
Close since there's no activity for more than 5 months. Feel free to open a new PR if you think the changes are still required.

**Pull request closed without merging**
